# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ForexAPI Website
    url: https://forexapi.co

status-website:
  baseUrl: /upptime
  name: ForexAPI Website Status
